name: Deploy to Railway

on:
  push:
    branches: [Develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      SVC_ID: docker-backend-get
      RAILWAY_TOKEN: ${{ 85370276-24aa-4b9d-9529-746955028f22 }}
    steps:
      - uses: actions/checkout@v3
      - run: railway up --service=${{ env.SVC_ID }}